language: go

services:
  - docker

script:
  - make

jobs:
  include:
    - stage: Push docker image
      if: tag IS present
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        - make docker.push
